2024-12-19 12:40:17,176 - [命令注入漏洞] 发现命令注入漏洞，负载: ; ls (2024-12-19 16:20:00)
2024-12-19 12:40:17,177 - [敏感数据暴露] 发现敏感数据暴露，负载: /admin (2024-12-19 16:20:05)
2024-12-19 12:40:17,177 - [暴力破解] 发现暴力破解，负载: POST /login?username=admin&password=123456 (2024-12-19 16:20:10)
2024-12-19 12:40:17,177 - [会话管理] 发现会话管理，负载: /user/profile (2024-12-19 16:20:15)
2024-12-19 12:40:17,177 - [不安全的文件上传] 发现不安全的文件上传，负载: /upload?file=malicious.exe (2024-12-19 16:20:20)
2024-12-19 12:40:17,177 - [跨站请求伪造] 发现跨站请求伪造，负载: /transfer?to=attacker&amount=1000 (2024-12-19 16:20:25)
2024-12-19 12:40:17,177 - [目录遍历漏洞] 发现目录遍历漏洞，负载: ../../../../etc/passwd (2024-12-19 16:20:30)
2024-12-19 12:40:17,177 - [SQL注入] 发现SQL注入，负载: OR 1=1 -- (2024-12-19 16:20:35)
2024-12-19 12:40:17,177 - [文件包含漏洞] 发现文件包含漏洞，负载: /file.php?file=../../../../etc/passwd (2024-12-19 16:20:40)
2024-12-19 12:40:17,177 - [HTTP头漏洞] 发现HTTP头漏洞，负载: Host: attacker.com (2024-12-19 16:20:45)
2024-12-19 12:40:17,177 - [端口扫描] 发现端口扫描，负载: nmap -p 80,443 192.168.1.1 (2024-12-19 16:20:50)
2024-12-19 12:40:24,158 - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000151A0FC2FD0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /
2024-12-19 12:40:24,362 - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000151A1001310>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /
2024-12-19 12:40:24,763 - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001519B3AD670>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /
2024-12-19 12:40:24,765 - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001519B3AD400>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /
2024-12-19 12:40:24,966 - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001519B3AD9A0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /
2024-12-19 12:40:25,368 - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001519B3A3C70>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /
2024-12-19 12:40:25,370 - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001519B3A3970>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /
2024-12-19 12:40:25,571 - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000151A1019520>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /
2024-12-19 12:40:25,972 - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000151A1019970>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /
2024-12-19 12:40:34,097 - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001519B3ADDF0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /
2024-12-19 12:40:34,302 - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000151A0FF3D00>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /
2024-12-19 12:40:34,704 - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001519B37B760>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /
2024-12-19 12:40:34,706 - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000151A102B340>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /
2024-12-19 12:40:34,907 - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000151A102BD60>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /
2024-12-19 12:40:35,309 - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000151A102B910>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /
2024-12-19 12:40:35,311 - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000151A1019940>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /
2024-12-19 12:40:35,513 - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001519B3ADB80>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /
2024-12-19 12:40:35,914 - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001519B3ADBB0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /
